# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build & Test

on:
  push:
  pull_request:
  workflow_call:
    inputs:
      RELEASE_VERSION:
        description: "Release Version"
        type: string
        required: false
        default: ""
      RELEASE_NOTES:
        description: "Release Notes"
        type: string
        required: false
        default: ""
    secrets:
      RESONITE_CLONE_TOKEN:
        required: true
env:
  ARTIFACT_NAME: "SampleMod"
  ASSEMBLY_NAME: "mpmxyz.SampleMod"
  PROJECT_FILE_MONKEY: "SampleModMonkey.csproj"
  ResonitePath: "${{ github.workspace }}/Download/Resonite"
  PROJECT_URL: "${{ github.server_url }}/${{ github.repository }}"
  PROJECT_PATH: "${{ github.workspace }}/repo"
  RELEASE_NOTES: "${{ inputs.RELEASE_NOTES }}"
  RELEASE_VERSION: "${{ inputs.RELEASE_VERSION }}"
  OUTPUT_FOLDER_MONKEY: "bin/MonkeyLoader/Release"
  TEST_FILE_MONKEY: "Test/Test.csproj"
  RESONITE_CLONE_REPO: "${{ github.repository_owner }}/ResoniteFiles"
defaults:
  run:
    working-directory: "./repo"
jobs:
  build-MonkeyLoader:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch repository
      uses: actions/checkout@v4
      with:
        path: ${{ env.PROJECT_PATH }}
    - name: Fetch latest Resonite
      uses: actions/checkout@v4
      with:
        repository: ${{ env.RESONITE_CLONE_REPO }}
        token: ${{ secrets.RESONITE_CLONE_TOKEN }}
        path: ${{ env.ResonitePath }}/..
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Prepare MonkeyLoader directories
      run: |
        mkdir -p "$PROJECT_PATH/MonkeyLoader GamePacks"
        mkdir -p "$PROJECT_PATH/MonkeyLoader Mods"
        mkdir -p "$ResonitePath/MonkeyLoader/GamePacks"
        mkdir -p "$ResonitePath/MonkeyLoader/Mods"
    - name: Fetch MonkeyLoader
      uses: robinraju/release-downloader@efa4cd07bd0195e6cc65e9e30c251b49ce4d3e51
      with:
        repository: Banane9/MonkeyLoader
        tag: v0.1.0-alpha
        fileName: "MonkeyLoader*.zip"
        out-file-path: MonkeyLoader/
    - name: Move files (MonkeyLoader)
      run: |
        unzip -o "${{ github.workspace }}/MonkeyLoader/MonkeyLoader*.zip" -d "$ResonitePath"
    - name: Restore dependencies
      run: |
        dotnet restore "${{ env.PROJECT_FILE_MONKEY }}"
    - name: Build (MonkeyLoader)
      run: dotnet build --no-restore --configuration "Release" "${{ env.PROJECT_FILE_MONKEY }}"
    - name: Test (MonkeyLoader)
      run: dotnet test --no-build --verbosity normal --configuration "Release" "${{ env.TEST_FILE_MONKEY }}"
    - name: Upload build artifacts (MonkeyLoader)
      if: ${{ inputs.RELEASE_VERSION }}
      uses: actions/upload-artifact@v3.1.3
      with: 
        name: "${{ env.ARTIFACT_NAME }}-MonkeyLoader"
        path: "${{ env.OUTPUT_FOLDER_MONKEY }}/${{ env.ASSEMBLY_NAME }}.${{ inputs.RELEASE_VERSION }}.nupkg"
