# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main", "workflow-dev" ]
  pull_request:
    branches: [ "main" ]
env:
  ResonitePath: "Download/Resonite"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch Repository
      uses: actions/checkout@v4
    - name: Fetch Resonite
      uses: actions/checkout@v4
      with:
        repository: mpmxyz/ResoniteFiles
        token: ${{ secrets.resonite_clone_token }}
        path: ${{ env.ResonitePath }}/..
    - name: Prepare Directories
      run: |
        mkdir -p "$ResonitePath/rml_libs"
        mkdir -p "$ResonitePath/Libraries"
        mkdir "MonkeyLoader GamePacks"
        mkdir "MonkeyLoader Mods"
    - name: Fetch MonkeyLoder
      uses: duhow/download-github-release-assets@v1.1.1
      with:
        repository: Banane9/MonkeyLoader
        release-id: latest
        target: MonkeyLoader/
        files: "MonkeyLoader-0.1.0-alpha.zip"
    - name: Fetch ResoniteModLoader
      uses: duhow/download-github-release-assets@v1.1.1
      with:
        repository: resonite-modding-group/ResoniteModLoader
        release-id: latest
        target: RML/
        files: "*.dll"
    - name: Move ResoniteModLoader Files
      run: |
        mv RML/0Harmony.dll "$ResonitePath/rml_libs/0Harmony.dll"
        mv RML/ResoniteModLoader.dll "$ResonitePath/Libraries/ResoniteModLoader.dll"
    - name: Move MonkeyLoader Files
      run: |
        unzip -o MonkeyLoader/MonkeyLoader-0.1.0-alpha.zip -d "$ResonitePath"
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Debug Resonite directory
      run: |
        ls $ResonitePath
        echo "!"
        ls $ResonitePath/MonkeyLoader
        echo "!"
        ls $ResonitePath/MonkeyLoader/GamePacks
    - name: Move MonkeyLoader GamePack
      run: |
        nuget init "$ResonitePath/MonkeyLoader/GamePacks" "MonkeyLoader GamePacks"
    - name: Debug build directory
      run: ls
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -Configuration "Release MonkeyLoader"
#    - name: Test
#      run: dotnet test --no-build --verbosity normal
    - name: LS
      run: ls
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with: 
        name: SampleMod.nupkg
        path: bin/Release MonkeyLoader/1.0.0/mpmxyz.SampleMod.nupkg
