
name: Publish NuGet packages on release

on:
  release:
    types: [published]
    
env:
  NUGET_PUBLISH_TARGET: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
  TEMP_NUGET_FOLDER: "nupkgs/"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch release NuGet packages
      uses: duhow/download-github-release-assets@v1.1.1
      with:
        repository: ${{ github.repository }}
        tag: ${{ github.ref_name }}
        target: ${{ env.TEMP_NUGET_FOLDER }}
        files: "*.nupkg"
    - name: Add repo owner's NuGet package source
      run: dotnet nuget add source --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name "publish_target" "${{ env.NUGET_PUBLISH_TARGET }}"
    - name: Publish to NuGet feed
      run: dotnet nuget push "${{ env.TEMP_NUGET_FOLDER }}/*.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source "publish_target"
